### ISSUE TITLE
Syncopation feature not working all the time

### ISSUE THREAD

**Issue by csbailey5t** [csbailey5t/prosody_plugin#2]
Currently, even when the poem is currently scanned, so that every line in the poem has three green check marks (stress, feet, meter), the syncopation toggle doesn't always show. 

It does work for me on the staging site for the poem "Thaw," but does not work for another person on Windows (using Firefox) on the same poem.

**Comment by ammonshepherd** [comment]
fixed by 3fc81ddb356a7a105533f3d8b854ee0bbafcd5f2
